// FIX-PROD-1
function fpVal(id){var el=document.getElementById(id);return el?el.value:'';}
function fpToggle(id){var el=document.getElementById(id);if(el)el.classList.toggle('hidden');}
function fpHide(id){var el=document.getElementById(id);if(el)el.classList.add('hidden');}
function fpSetMsg(id,t,ok){var el=document.getElementById(id);if(!el)return;el.textContent=t||'';el.style.color=ok?'#059669':'#dc2626';}
function fpUser(){return (typeof WEB_USER!=='undefined'&&WEB_USER)?(WEB_USER.username||''):'';}
async function fpPost(path,body){var r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});var j=await r.json().catch(function(){return{};});if(!r.ok)throw new Error(j.error||('HTTP '+r.status));return j;}
function fpFillStations(){['fwStation','fdStation','fmStation','plStation'].forEach(function(id){var el=document.getElementById(id);if(el&&el.options.length===0){var html='';for(var k in STATIONS){html+='<option value="'+k+'">'+STATIONS[k]+'</option>';}el.innerHTML=html;}});}
function fpFillPlans(){var el=document.getElementById('fmPlan');if(!el)return;var plans=(typeof cache!=='undefined'&&cache.mntPlans)||[];var html='<option value="">بدون ارجاع به برنامه PM</option>';plans.forEach(function(pl){html+='<option value="'+pl.id+'">'+(pl.title||'')+'</option>';});el.innerHTML=html;}
function fpCell(c,r){var v=r[c.key];if(c.num)return '<td>'+groupFa(v)+'</td>';if(c.date)return '<td>'+fmtDate(v)+'</td>';if(c.station)return '<td>'+stationFa(v)+'</td>';if(c.wt)return '<td>'+wtypeFa(v)+'</td>';if(c.chip)return '<td>'+(Number(v)?'<span class="chip ok">مطابق</span>':'<span class="chip no">مغایر</span>')+'</td>';if(c.src)return '<td>'+(v==='sensor'?'سنسور':'دستی')+'</td>';return '<td>'+esc(v==null?'':v)+'</td>';}
function fpRenderList(tab,rows){cache['list_'+tab]=rows||[];var t=document.getElementById('tbl-'+tab);if(!t)return;var cols=COLS[tab]||[];var html='<thead><tr>'+cols.map(function(c){return '<th>'+esc(c.label)+'</th>';}).join('')+'</tr></thead><tbody>';if(!rows||!rows.length){html+='<tr><td colspan="'+cols.length+'" class="empty">رکوردی ثبت نشده است.</td></tr>';}else{rows.slice().reverse().forEach(function(r){html+='<tr>'+cols.map(function(c){return fpCell(c,r);}).join('')+'</tr>';});}t.innerHTML=html+'</tbody>';}
function exportList(k,fname,title,cols){downloadCsv(fname,cols,cache['list_'+k]||[],title);}
async function loadProduction(){fpRenderList('production',await getJson('/api/production'));}
async function loadWaste(){fpRenderList('waste',await getJson('/api/waste'));}
async function loadDowntime(){fpRenderList('downtime',await getJson('/api/downtime'));}
async function loadQuality(){fpRenderList('quality',await getJson('/api/quality'));}
async function loadMaintenance(){
var j=await getJson('/api/maintenance-extra');
cache.mntLogs=j.logs||[];cache.mntPlans=j.plans||[];fpFillPlans();
var t=document.getElementById('tbl-mntlogs');
if(t){var html='<thead><tr><th>تاریخ</th><th>ایستگاه</th><th>نوع</th><th>اولویت</th><th>مدت(دقیقه)</th><th>تکنسین</th></tr></thead><tbody>';if(!cache.mntLogs.length)html+='<tr><td colspan="6" class="empty">رکوردی ثبت نشده</td></tr>';cache.mntLogs.slice().reverse().forEach(function(r){html+='<tr><td>'+esc(r.work_date||'-')+'</td><td>'+stationFa(r.machine_id)+'</td><td>'+esc(r.work_type||'-')+'</td><td>'+esc(r.priority||'-')+'</td><td>'+groupFa(r.duration_minutes)+'</td><td>'+esc(r.technician||'-')+'</td></tr>';});t.innerHTML=html+'</tbody>';}
var tp=document.getElementById('tbl-pmplans');
if(tp){var h2='<thead><tr><th>ایستگاه</th><th>عنوان</th><th>دوره(روز)</th><th>آخرین انجام</th></tr></thead><tbody>';if(!cache.mntPlans.length)h2+='<tr><td colspan="4" class="empty">برنامه‌ای تعریف نشده</td></tr>';cache.mntPlans.forEach(function(pl){h2+='<tr><td>'+stationFa(pl.machine_id)+'</td><td>'+esc(pl.title||'')+'</td><td>'+groupFa(pl.interval_days)+'</td><td>'+esc(pl.last_done||'-')+'</td></tr>';});tp.innerHTML=h2+'</tbody>';}
var md=document.getElementById('tbl-maintenance');
if(md){var dl=(cache.mntLogs||[]).slice(0,10);var h3='<thead><tr><th>تاریخ</th><th>ایستگاه</th><th>نوع</th><th>مدت</th></tr></thead><tbody>';if(!dl.length)h3+='<tr><td colspan="4" class="empty">-</td></tr>';dl.forEach(function(r){h3+='<tr><td>'+esc(r.work_date||'-')+'</td><td>'+stationFa(r.machine_id)+'</td><td>'+esc(r.work_type||'-')+'</td><td>'+groupFa(r.duration_minutes)+'</td></tr>';});md.innerHTML=h3+'</tbody>';}
}
(function(){
fpFillStations();
var tmap={btnAddProduction:'formProduction',btnAddWaste:'formWaste',btnAddDowntime:'formDowntime',btnAddQuality:'formQuality',btnAddMaintenance:'formMaintenance',btnAddPlan:'formPlan'};
Object.keys(tmap).forEach(function(id){var el=document.getElementById(id);if(el)el.addEventListener('click',function(){fpFillStations();if(id==='btnAddMaintenance'){fpFillPlans();}fpToggle(tmap[id]);});});
var cmap={fpCancel:'formProduction',fwCancel:'formWaste',fdCancel:'formDowntime',fqCancel:'formQuality',fmCancel:'formMaintenance',plCancel:'formPlan'};
Object.keys(cmap).forEach(function(id){var el=document.getElementById(id);if(el)el.addEventListener('click',function(){fpHide(cmap[id]);});});
document.getElementById('fpSave').addEventListener('click',async function(){try{await fpPost('/api/entry/production',{operator_id:fpUser(),product_id:fpVal('fpProduct'),shift_id:fpVal('fpShift'),good_quantity:Number(fpVal('fpQty'))||0,pallet_count:Number(fpVal('fpPallets'))||0,machine_id:'st-pack',description:fpVal('fpDesc')});fpSetMsg('fpMsg','ثبت با موفقیت انجام شد ✓',true);fpHide('formProduction');await loadProduction();}catch(e){fpSetMsg('fpMsg','خطا: '+e.message,false);}});
document.getElementById('fwSave').addEventListener('click',async function(){try{await fpPost('/api/entry/waste',{operator_id:fpUser(),shift_id:fpVal('fwShift'),machine_id:fpVal('fwStation'),reason_id:fpVal('fwReason'),waste_type:fpVal('fwType'),quantity:Number(fpVal('fwQty'))||0,description:fpVal('fwDesc')});fpSetMsg('fwMsg','ثبت با موفقیت انجام شد ✓',true);fpHide('formWaste');await loadWaste();}catch(e){fpSetMsg('fwMsg','خطا: '+e.message,false);}});
document.getElementById('fdSave').addEventListener('click',async function(){try{var fr=document.getElementById('formDowntime');var st=parseJalaliDateTime(readJalaliValue(fr,'fds'),fpVal('fdStartTime'));var en=parseJalaliDateTime(readJalaliValue(fr,'fde'),fpVal('fdEndTime'));if(!st||!en){fpSetMsg('fdMsg','تاریخ شمسی معتبر وارد کنید.',false);return;}await fpPost('/api/entry/downtime',{shift_id:fpVal('fdShift'),machine_id:fpVal('fdStation'),reason_id:fpVal('fdReason'),is_unplanned:Number(fpVal('fdType')),start_time:st.toISOString(),end_time:en.toISOString(),description:fpVal('fdDesc')});fpSetMsg('fdMsg','ثبت با موفقیت انجام شد ✓',true);fpHide('formDowntime');await loadDowntime();}catch(e){fpSetMsg('fdMsg','خطا: '+e.message,false);}});
document.getElementById('fqSave').addEventListener('click',async function(){try{await fpPost('/api/entry/quality',{operator_id:fpUser(),heat_number:fpVal('fqHeat'),rebar_size:Number(fpVal('fqSize'))||0,yield_strength:Number(fpVal('fqPressure'))||0,tensile_strength:Number(fpVal('fqLining'))||0,elongation_percent:Number(fpVal('fqDrop'))||0,bend_test_passed:Number(fpVal('fqLeak')),visual_inspection:Number(fpVal('fqVisual')),description:fpVal('fqDesc')});fpSetMsg('fqMsg','ثبت با موفقیت انجام شد ✓',true);fpHide('formQuality');await loadQuality();}catch(e){fpSetMsg('fqMsg','خطا: '+e.message,false);}});
document.getElementById('fmSave').addEventListener('click',async function(){try{await fpPost('/api/entry/maintenance',{machine_id:fpVal('fmStation'),work_type:fpVal('fmType'),priority:fpVal('fmPriority'),work_date:readJalaliValue(document.getElementById('formMaintenance'),'fmd'),duration_minutes:Number(fpVal('fmDuration'))||0,technician:fpVal('fmTech'),cost:Number(fpVal('fmCost'))||0,parts:fpVal('fmParts'),root_cause:fpVal('fmRootCause'),action_taken:fpVal('fmAction'),description:fpVal('fmDesc'),plan_id:fpVal('fmPlan')});fpSetMsg('fmMsg','ثبت با موفقیت انجام شد ✓',true);fpHide('formMaintenance');await loadMaintenance();}catch(e){fpSetMsg('fmMsg','خطا: '+e.message,false);}});
document.getElementById('plSave').addEventListener('click',async function(){try{await fpPost('/api/pm/plan',{machine_id:fpVal('plStation'),title:fpVal('plTitle'),interval_days:Number(fpVal('plInterval'))||0,last_done:readJalaliValue(document.getElementById('formPlan'),'pllast'),responsible:fpVal('plResp'),priority:fpVal('plPriority'),notes:fpVal('plNotes')});fpSetMsg('plMsg','برنامه PM ثبت شد ✓',true);fpHide('formPlan');await loadMaintenance();}catch(e){fpSetMsg('plMsg','خطا: '+e.message,false);}});
})();